POST http://192.168.1.10:3333/
content-type: application/json

{
    "tableName": "FUNCIONARIOS",
    "params": {
        "funcionarioId": 55,
        "nome": "Joaquim da silva",
        "situacao": 1,
        "funcaoId": 10,
        "cpf": "111.111.111-11",
        "obraId": 55,
        "empresaId": 30,
        "nascimento": 333,
        "telefoneFixo": "31-3827-2540",
        "telefoneCelular": "31-3827-2540",
        "email": "csadas@gmail.com",
        "apelido": "casa",
        "foto": "asdasdasdas.png"   
    }
}