POST http://192.168.1.10:3333/db/insert
content-type: application/json

{
    "tableName": "EMPRESAS",
    "params": {
        "nomeFantasia": "Alterosa",
        "cnpj": "31.107.606/0001-54",
        "razaoSocial": "Alterosa",
        "nomeResponsavel": "nomeResponsavel",
        "telefoneFixo": "(21)99852-8453"
        }
}

###
POST http://192.168.1.10:3333/db/insert
content-type: application/json

{
    "tableName": "OBRAS",
    "params": {
        "bairro": "Vargem Grande",
        "logradouro": "Alagoa",
        "cidade": "Teresópolis",
        "estado": "RJ",
        "telefoneFixo": "(21)99852-8453"
        }
}
###
POST http://192.168.1.10:3333/db/read
content-type: application/json

{
    "tableName": "OBRAS"
}
###
POST http://192.168.1.10:3333/db/insert
content-type: application/json

{
    "tableName": "FUNCAO",
    "params": {
        "nomeFuncao": "Ajudante"
        }
}

###
POST http://192.168.1.10:3333/db/insert
content-type: application/json

{
    "tableName": "FUNCIONARIOS",
    "params": {
        "nome": "Joaquim da silva",
        "situacao": 1,        
        "cpf": "111.111.111-11",
        "nascimento": 333,
        "funcaoId": 1,
        "obraId": 1,
        "empresaId": 1,                
        "telefoneFixo": "31-3827-2540",
        "telefoneCelular": "31-3827-2540",
        "email": "csadas@gmail.com",
        "apelido": "casa",
        "foto": "asdasdasdas.png"   
    }
}

###
POST http://192.168.1.10:3335/db/insert
content-type: application/json

{
    "tableName": "USUARIOS",
    "params":{
        "uid": "ygoT01gDlzWdpeUyx0HV0C6GH1q2",
        "name": "test",
        "photoUrl": "",
        "email":"test@test.com",
        "permission": "0,1,2,3",
        "situacao" : "1"
    }
}

###
POST http://192.168.1.10:3335/db/read
content-type: application/json

{
    "tableName": "USUARIOS",
    "item": "uid",
    "value": "353lKvjVRYhu7mqrbdt2qCUfofW2"
}